title: 'papa.musicreleases::lang.releases'
modelClass: Papa\Musicreleases\Models\Release
list: $/papa/musicreleases/models/release/columns.yaml
recordUrl: 'papa/musicreleases/releases/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
