title: 'papa.musicreleases::lang.releasetypes'
modelClass: Papa\Musicreleases\Models\Releasetype
list: $/papa/musicreleases/models/releasetype/columns.yaml
recordUrl: 'papa/musicreleases/releasetypes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
