title: 'papa.musicreleases::lang.artists'
modelClass: Papa\Musicreleases\Models\Artist
list: $/papa/musicreleases/models/artist/columns.yaml
recordUrl: 'papa/musicreleases/artists/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
